services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - 5433:5432
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - polykanban-postgres-data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:12
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
      FLYWAY_LOCATIONS: filesystem:/flyway/migration
    command:
      - migrate
    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./db/migration:/flyway/migration

  backend:
    build: ./backend-node-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./backend-node-api:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend

volumes:
  polykanban-postgres-data:
