CREATE TABLE IF NOT EXISTS "card" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"position" INTEGER,
	"title" VARCHAR(255),
	"description" TEXT,
	"list_id" INTEGER,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);
