ALTER TABLE "card"
ADD FOREIGN KEY("list_id") REFERENCES "list"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "card_tag"
ADD FOREIGN KEY("id_card") REFERENCES "card"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "card_tag"
ADD FOREIGN KEY("id_tag") REFERENCES "tag"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;